
# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3
# [END runtime]

env_variables:
    PUBSUB_TOPIC: notes-topic
    PUBSUB_VERIFICATION_TOKEN: <PUBSUB_VERIFICATION_TOKEN>
